import type { SensitivePathSpec } from './SensitivePath.js';
import { POSIX_PLATFORMS, PLATFORMS } from '../value-objects/Platform.js';

const ALL = PLATFORMS;
const POSIX = POSIX_PLATFORMS;
const MAC = ['darwin'] as const;
const LINUX = ['linux'] as const;
const WINDOWS = ['win32'] as const;

/**
 * The single source of truth behind the B and P rule families and behind the
 * sandbox profile itself (spec §6.4). Data, not code: adding a path must never
 * mean editing a rule.
 *
 * Every row carries a rationale because a registry nobody can audit is a
 * registry nobody trusts.
 */
export const SENSITIVE_PATHS: readonly SensitivePathSpec[] = Object.freeze([
  // ── Credentials ────────────────────────────────────────────────────────────
  {
    id: 'ssh-keys',
    pattern: '~/.ssh/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Private keys grant access to every host and repository the user can reach.',
  },
  {
    id: 'aws-credentials',
    pattern: '~/.aws/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Long-lived cloud access keys; a leak is an account takeover.',
  },
  {
    id: 'gcloud-credentials',
    pattern: '~/.config/gcloud/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Google Cloud refresh tokens and application default credentials.',
  },
  {
    id: 'kube-config',
    pattern: '~/.kube/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Cluster certificates and tokens, usually with administrative rights.',
  },
  {
    id: 'docker-config',
    pattern: '~/.docker/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Registry authentication tokens, and a daemon socket path on some setups.',
  },
  {
    id: 'netrc',
    pattern: '~/.netrc',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Plaintext machine credentials used by curl, git and ftp clients.',
  },
  {
    id: 'npmrc',
    pattern: '~/.npmrc',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Publish tokens; also a registry override that redirects every install.',
  },
  {
    id: 'pypirc',
    pattern: '~/.pypirc',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'PyPI upload tokens, enough to publish a package under the user name.',
  },
  {
    id: 'gh-hosts',
    pattern: '~/.config/gh/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'GitHub CLI OAuth tokens with repository and workflow scope.',
  },
  {
    id: 'rclone-config',
    pattern: '~/.config/rclone/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Credentials for every configured remote storage backend.',
  },
  {
    id: 'macos-keychain',
    pattern: '~/Library/Keychains/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale: "The user's credential store; everything they ever saved lives here.",
  },
  {
    // Outside the home directory, where the macOS profile still permits broad
    // reads. The file is world-readable by default, so nothing but this rule
    // keeps it from leaving with the agent.
    id: 'macos-system-keychain',
    pattern: '/Library/Keychains/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale:
      'The machine-wide credential store: Wi-Fi and 802.1X secrets, and certificates whose private keys are guarded by a daemon that a stolen copy never has to ask.',
  },
  {
    id: 'macos-ssh-host-keys',
    pattern: '/private/etc/ssh/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale:
      'Host private keys, present once Remote Login is enabled; they authenticate the machine itself.',
  },
  {
    id: 'gnupg',
    pattern: '~/.gnupg/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Signing and encryption private keys.',
  },
  {
    id: 'env-file-outside-workspace',
    pattern: '**/.env',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    outsideWorkspaceOnly: true,
    rationale: 'Another project’s environment file is the fastest route to its secrets.',
  },
  {
    id: 'env-variant-outside-workspace',
    pattern: '**/.env.*',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    outsideWorkspaceOnly: true,
    rationale: 'Environment overlays of neighbouring projects hold the same secrets.',
  },

  // ── Browser profiles ───────────────────────────────────────────────────────
  {
    id: 'chrome-profile-macos',
    pattern: '~/Library/Application Support/Google/Chrome/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale: 'Session cookies and saved passwords of every logged-in service.',
  },
  {
    id: 'chromium-profile-linux',
    pattern: '~/.config/google-chrome/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: LINUX,
    rationale: 'Session cookies and saved passwords of every logged-in service.',
  },
  {
    id: 'safari-profile',
    pattern: '~/Library/Safari/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale: 'Browsing history and site data, including authenticated sessions.',
  },
  {
    id: 'firefox-profile',
    pattern: '~/.mozilla/firefox/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'logins.json and cookies.sqlite hold decryptable saved credentials.',
  },
  {
    id: 'chrome-profile-windows',
    pattern: '~/appdata/local/google/chrome/user data/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'Chrome cookies and saved sessions provide authenticated access to web services.',
  },
  {
    id: 'edge-profile-windows',
    pattern: '~/appdata/local/microsoft/edge/user data/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'Edge cookies and saved sessions provide authenticated access to web services.',
  },
  {
    id: 'firefox-profile-windows',
    pattern: '~/appdata/roaming/mozilla/firefox/**',
    category: 'credential',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'Firefox profiles contain saved logins, cookies and authenticated sessions.',
  },

  // ── Persistence (vector V9) ────────────────────────────────────────────────
  {
    id: 'zsh-env',
    pattern: '~/.zshenv',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Read by every zsh invocation including non-interactive ones: the best foothold on macOS.',
  },
  {
    id: 'zsh-rc',
    pattern: '~/.zshrc',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Runs on every interactive shell; survives deletion of the repository.',
  },
  {
    id: 'bash-rc',
    pattern: '~/.bashrc',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Runs on every interactive bash shell.',
  },
  {
    id: 'bash-profile',
    pattern: '~/.bash_profile',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Runs on every bash login shell.',
  },
  {
    id: 'sh-profile',
    pattern: '~/.profile',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Runs on login for every POSIX shell.',
  },
  {
    id: 'fish-config',
    pattern: '~/.config/fish/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'config.fish and conf.d run on every fish shell start.',
  },
  {
    id: 'git-config',
    pattern: '~/.gitconfig',
    category: 'persistence',
    // Reading is what makes `git` usable at all — measured, not assumed: with
    // the file unreadable git refuses every command. Writing installs
    // core.hooksPath, which is vector V9, so it stays out of runtime reach.
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'core.hooksPath, credential.helper and shell aliases each execute code.',
  },
  {
    id: 'git-config-xdg',
    pattern: '~/.config/git/**',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'XDG location of the same git configuration.',
  },
  {
    id: 'ssh-authorized-keys',
    pattern: '~/.ssh/authorized_keys',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Appending a key grants permanent remote access to the machine.',
  },
  {
    id: 'ssh-client-config',
    pattern: '~/.ssh/config',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'ProxyCommand and LocalCommand execute on every outgoing connection.',
  },
  {
    id: 'launch-agents',
    pattern: '~/Library/LaunchAgents/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale: 'A plist here runs at every login without any further user action.',
  },
  {
    id: 'systemd-user-units',
    pattern: '~/.config/systemd/user/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: LINUX,
    rationale: 'A user unit starts at login and restarts itself on failure.',
  },
  {
    id: 'powershell-core-profile',
    pattern: '~/documents/powershell/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'PowerShell profile scripts execute whenever a PowerShell session starts.',
  },
  {
    id: 'windows-powershell-profile',
    pattern: '~/documents/windowspowershell/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'Windows PowerShell profile scripts execute whenever a legacy session starts.',
  },
  {
    id: 'windows-startup-folder',
    pattern: '~/appdata/roaming/microsoft/windows/start menu/programs/startup/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: WINDOWS,
    rationale: 'Programs placed in the per-user Startup folder execute at every login.',
  },
  {
    id: 'crontab-macos',
    pattern: '/private/var/at/tabs/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: MAC,
    rationale: 'Scheduled execution that outlives the session.',
  },
  {
    id: 'crontab-linux',
    pattern: '/var/spool/cron/**',
    category: 'persistence',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: LINUX,
    rationale: 'Scheduled execution that outlives the session.',
  },

  // ── Shell history (vector V10) ─────────────────────────────────────────────
  {
    id: 'zsh-history',
    pattern: '~/.zsh_history',
    category: 'history',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Command lines regularly contain tokens pasted as arguments.',
  },
  {
    id: 'bash-history',
    pattern: '~/.bash_history',
    category: 'history',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Command lines regularly contain tokens pasted as arguments.',
  },
  {
    id: 'psql-history',
    pattern: '~/.psql_history',
    category: 'history',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: POSIX,
    rationale: 'Database queries with embedded connection strings and data.',
  },
  {
    id: 'node-repl-history',
    pattern: '~/.node_repl_history',
    category: 'history',
    readTier: 2,
    writeTier: 2,
    onRead: 'block',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'REPL sessions frequently contain pasted keys.',
  },

  // ── Agent and agentkeeper configuration (vectors V2, V8; rules B003/B005) ──
  {
    id: 'claude-settings',
    pattern: '~/.claude/settings*.json',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'SessionStart and PreToolUse hooks here run on the next agent start.',
  },
  {
    id: 'claude-config',
    pattern: '~/.claude.json',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Global agent configuration, including approved MCP servers.',
  },
  {
    id: 'gemini-settings',
    pattern: '~/.gemini/settings.json',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Global agent configuration, including tool and MCP permissions.',
  },
  {
    id: 'cursor-mcp',
    pattern: '~/.cursor/mcp.json',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'MCP server definitions execute an arbitrary command at session start.',
  },
  {
    id: 'agentkeeper-state',
    pattern: '~/.agentkeeper/**',
    category: 'persistence',
    readTier: 1,
    writeTier: 2,
    onRead: 'observe',
    onWrite: 'block',
    platforms: ALL,
    rationale: 'Self-protection: an agent that can edit its own allowlist has none.',
  },

  // ── Ordinary developer configuration (tier 1) ─────────────────────────────
  {
    id: 'xdg-tool-config',
    pattern: '~/.config/**',
    category: 'config',
    readTier: 1,
    writeTier: 1,
    onRead: 'observe',
    onWrite: 'observe',
    platforms: POSIX,
    rationale: 'Editor and tool settings: useful to the agent, cheap to grant, no secrets by itself.',
  },
]);
