import {
  hasMarkers,
  stripMarkers,
  withMarkers,
  type Integration,
  type PlannedChange,
} from './Integration.js';
import type { AbsolutePath } from '../../domain/value-objects/AbsolutePath.js';
import type { Platform } from '../../domain/value-objects/Platform.js';
import type { FileSystem } from '../../application/ports/index.js';

/** Agents whose invocation is wrapped by a shell function (spec §4.7). */
const WRAPPED_AGENTS = ['claude', 'gemini', 'codex', 'cursor-agent', 'aider'];

/**
 * Shell functions that route each agent through `agent-guard run`.
 *
 * Two files, not one: the rc file gets a single `source` line inside markers,
 * everything else lives in `~/.agent-guard/shell-init.sh`. That makes uninstall
 * exact — one marked block removed, one file deleted — instead of a fuzzy
 * search-and-replace through a file the user has been editing for years.
 */
export class ShellFunctionsIntegration implements Integration {
  readonly id = 'shell-functions';
  readonly description = 'Route claude/gemini/codex through agent-guard automatically';

  constructor(
    private readonly files: FileSystem,
    private readonly home: AbsolutePath,
    private readonly stateDir: AbsolutePath,
    private readonly rcFiles: readonly string[] = ['.zshrc', '.bashrc'],
  ) {}

  async plan(): Promise<readonly PlannedChange[]> {
    const scriptPath = this.stateDir.join('shell-init.sh');
    const changes: PlannedChange[] = [
      {
        path: scriptPath,
        before: await this.files.read(scriptPath),
        after: this.script(),
        summary: 'Shell functions that wrap each agent',
      },
    ];

    for (const name of this.rcFiles) {
      const rcPath = this.home.join(name);
      const before = await this.files.read(rcPath);
      if (before === null) continue; // do not create a shell rc file nobody uses
      if (hasMarkers(before)) continue;

      changes.push({
        path: rcPath,
        before,
        after: `${before}${before.endsWith('\n') ? '' : '\n'}${withMarkers(
          `[ -f "${scriptPath.value}" ] && . "${scriptPath.value}"`,
        )}`,
        summary: 'One line sourcing the shell functions above',
      });
    }
    return changes;
  }

  async isInstalled(): Promise<boolean> {
    for (const name of this.rcFiles) {
      if (hasMarkers(await this.files.read(this.home.join(name)))) return true;
    }
    return false;
  }

  /** Reverse of `plan`: strip the marked block, delete the script. */
  async uninstallPlan(): Promise<readonly PlannedChange[]> {
    const changes: PlannedChange[] = [
      {
        path: this.stateDir.join('shell-init.sh'),
        before: await this.files.read(this.stateDir.join('shell-init.sh')),
        after: null,
        summary: 'Remove the shell functions',
      },
    ];

    for (const name of this.rcFiles) {
      const rcPath = this.home.join(name);
      const before = await this.files.read(rcPath);
      if (!hasMarkers(before)) continue;
      changes.push({
        path: rcPath,
        before,
        after: stripMarkers(before as string),
        summary: 'Remove the sourcing line',
      });
    }
    return changes;
  }

  private script(): string {
    const functions = WRAPPED_AGENTS.map(
      (agent) =>
        `${agent}() {\n` +
        `  if [ -n "\${AGENT_GUARD_BYPASS:-}" ]; then command ${agent} "$@"; return $?; fi\n` +
        `  agent-guard run -- ${agent} "$@"\n` +
        `}`,
    ).join('\n\n');

    return [
      '# Generated by agent-guard. Sourced from your shell rc file.',
      '# Remove with: agent-guard uninstall',
      '#',
      '# AGENT_GUARD_BYPASS=1 skips the wrapper for one command. It is meant for',
      '# you, from your own terminal — the agent itself is refused by AG-B006.',
      '',
      functions,
      '',
    ].join('\n');
  }
}

/**
 * How an installed hook is recognised later.
 *
 * Deliberately not the binary name: `init` writes an absolute path to the
 * installed entry point, so a marker like "agent-guard hook" never matches and
 * `uninstall` silently leaves the hook behind. The invariant that matters is
 * that install and uninstall agree, so both use this one constant.
 */
const HOOK_MARKER = 'hook pretooluse';

interface HookSettings {
  hooks?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Registers the `PreToolUse` hook in the user's own agent settings (E3).
 *
 * Merges into the existing JSON rather than replacing it: the file usually
 * already holds settings somebody cares about.
 */
export class ClaudeHookIntegration implements Integration {
  readonly id = 'pretooluse-hook';
  readonly description = 'Observe and refuse tool calls inside the sandbox';

  constructor(
    private readonly files: FileSystem,
    private readonly home: AbsolutePath,
    private readonly binary: string,
  ) {}

  private get settingsPath(): AbsolutePath {
    return this.home.join('.claude/settings.json');
  }

  async plan(): Promise<readonly PlannedChange[]> {
    const before = await this.files.read(this.settingsPath);
    const settings = parseSettings(before);
    const hooks = { ...(settings.hooks ?? {}) };
    hooks['PreToolUse'] = [
      {
        matcher: '*',
        hooks: [{ type: 'command', command: `${this.binary} ${HOOK_MARKER}` }],
      },
    ];

    return [
      {
        path: this.settingsPath,
        before,
        after: `${JSON.stringify({ ...settings, hooks }, null, 2)}\n`,
        summary: 'Register the agent-guard PreToolUse hook',
      },
    ];
  }

  async isInstalled(): Promise<boolean> {
    const raw = await this.files.read(this.settingsPath);
    return raw !== null && raw.includes(HOOK_MARKER);
  }

  async uninstallPlan(): Promise<readonly PlannedChange[]> {
    const before = await this.files.read(this.settingsPath);
    if (before === null || !before.includes(HOOK_MARKER)) return [];

    const settings = parseSettings(before);
    const hooks = { ...(settings.hooks ?? {}) };
    delete hooks['PreToolUse'];
    const next = Object.keys(hooks).length === 0 ? withoutHooks(settings) : { ...settings, hooks };

    return [
      {
        path: this.settingsPath,
        before,
        after: `${JSON.stringify(next, null, 2)}\n`,
        summary: 'Remove the agent-guard PreToolUse hook',
      },
    ];
  }
}

/**
 * A global git hook path, so a fresh clone is scanned before it is opened (E1).
 *
 * `core.hooksPath` is itself vector V9, which is why agent-guard chains to any
 * existing hook rather than replacing it, and never sets the git setting
 * silently — `init` shows the change and asks.
 */
export class GitHookIntegration implements Integration {
  readonly id = 'git-hooks';
  readonly description = 'Scan a repository after clone, checkout and merge';

  constructor(
    private readonly files: FileSystem,
    private readonly stateDir: AbsolutePath,
    private readonly binary: string,
    private readonly existingHooksPath: string | null,
  ) {}

  async plan(): Promise<readonly PlannedChange[]> {
    const directory = this.stateDir.join('git-hooks');
    const changes: PlannedChange[] = [];

    for (const name of ['post-checkout', 'post-merge']) {
      const path = directory.join(name);
      changes.push({
        path,
        before: await this.files.read(path),
        after: this.hookScript(name),
        summary: `git ${name} hook`,
      });
    }
    return changes;
  }

  async isInstalled(): Promise<boolean> {
    return this.files.exists(this.stateDir.join('git-hooks/post-checkout'));
  }

  async uninstallPlan(): Promise<readonly PlannedChange[]> {
    const directory = this.stateDir.join('git-hooks');
    return Promise.all(
      ['post-checkout', 'post-merge'].map(async (name) => ({
        path: directory.join(name),
        before: await this.files.read(directory.join(name)),
        after: null,
        summary: `Remove the git ${name} hook`,
      })),
    );
  }

  /** Chains to whatever was there before: husky and lefthook keep working. */
  private hookScript(name: string): string {
    const chain =
      this.existingHooksPath === null
        ? ''
        : `\n# Chain to the hooks that were configured before agent-guard.\n` +
          `[ -x "${this.existingHooksPath}/${name}" ] && "${this.existingHooksPath}/${name}" "$@"\n`;

    return [
      '#!/bin/sh',
      '# Generated by agent-guard. Remove with: agent-guard uninstall',
      'set -e',
      chain,
      `${this.binary} scan --quiet --source git-${name} || true`,
      '',
    ].join('\n');
  }
}

/** The resident watcher (E2): launchd on macOS, a user unit on Linux. */
export class DaemonIntegration implements Integration {
  readonly id = 'daemon';
  readonly description = 'Watch for persistence changes outside the sandbox';

  constructor(
    private readonly files: FileSystem,
    private readonly home: AbsolutePath,
    private readonly platform: Platform,
    private readonly binary: string,
  ) {}

  private get unitPath(): AbsolutePath {
    return this.platform === 'darwin'
      ? this.home.join('Library/LaunchAgents/dev.agent-guard.watcher.plist')
      : this.home.join('.config/systemd/user/agent-guard.service');
  }

  async plan(): Promise<readonly PlannedChange[]> {
    if (this.platform === 'win32') return [];
    return [
      {
        path: this.unitPath,
        before: await this.files.read(this.unitPath),
        after: this.platform === 'darwin' ? this.plist() : this.unit(),
        summary: 'Start the watcher at login (user level, never root)',
      },
    ];
  }

  async isInstalled(): Promise<boolean> {
    return this.files.exists(this.unitPath);
  }

  async uninstallPlan(): Promise<readonly PlannedChange[]> {
    return [
      {
        path: this.unitPath,
        before: await this.files.read(this.unitPath),
        after: null,
        summary: 'Remove the watcher',
      },
    ];
  }

  private plist(): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.agent-guard.watcher</string>
  <key>ProgramArguments</key>
  <array><string>${this.binary}</string><string>daemon</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
`;
  }

  private unit(): string {
    return `[Unit]
Description=agent-guard persistence watcher

[Service]
ExecStart=${this.binary} daemon
Restart=on-failure
Nice=10

[Install]
WantedBy=default.target
`;
  }
}

function parseSettings(raw: string | null): HookSettings {
  if (raw === null) return {};
  try {
    const parsed: unknown = JSON.parse(raw);
    return typeof parsed === 'object' && parsed !== null ? (parsed as HookSettings) : {};
  } catch {
    return {};
  }
}

function withoutHooks(settings: HookSettings): Record<string, unknown> {
  const { hooks: _removed, ...rest } = settings;
  return rest;
}
